BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "AutogiroForetag" (
	"ID"	INTEGER,
	"Foretagsnamn"	TEXT NOT NULL UNIQUE,
	"Bankgiro"	TEXT,
	"Plusgiro"	TEXT,
	"MottagarID"	TEXT,
	"Noteringar"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GodManProfiler" (
	"ID"	INTEGER,
	"Fornamn"	TEXT,
	"Efternamn"	TEXT,
	"Personnummer"	TEXT UNIQUE,
	"Adress"	TEXT,
	"Postnummer"	TEXT,
	"Postort"	TEXT,
	"Telefon"	TEXT,
	"Mobil"	TEXT,
	"Epost"	TEXT,
	"IsCurrentUser"	INTEGER DEFAULT 0,
	"Clearingnummer"	TEXT,
	"Kontonummer"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "HuvudmanArsrakningPoster" (
	"ID"	INTEGER,
	"HuvudmanPnr"	TEXT NOT NULL,
	"ArsrakningAr"	INTEGER NOT NULL,
	"PostKod"	TEXT NOT NULL,
	"Summa"	REAL,
	"BilagaRef"	TEXT,
	"OFnotRef"	TEXT,
	UNIQUE("HuvudmanPnr","ArsrakningAr","PostKod"),
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("HuvudmanPnr") REFERENCES "huvudman"("PERSONNUMMER") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "HuvudmanBankkonton" (
	"ID"	INTEGER,
	"HuvudmanPnr"	TEXT NOT NULL,
	"Typ"	TEXT NOT NULL,
	"RadNr"	INTEGER NOT NULL,
	"Beskrivning"	TEXT,
	"Kronor"	REAL DEFAULT 0.0,
	"BilagaRef"	TEXT,
	"OFnot"	TEXT,
	"pairId"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("HuvudmanPnr") REFERENCES "huvudman"("PERSONNUMMER") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "HuvudmanDokument" (
	"ID"	INTEGER,
	"HuvudmanPnr"	TEXT NOT NULL,
	"DokumentTyp"	TEXT NOT NULL,
	"OriginalFilnamn"	TEXT NOT NULL,
	"StoredFilnamn"	TEXT NOT NULL,
	"StoredPath"	TEXT NOT NULL,
	"CreatedAt"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("HuvudmanPnr") REFERENCES "huvudman"("PERSONNUMMER") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "HuvudmanOvrigaTillgangar" (
	"ID"	INTEGER,
	"HuvudmanPnr"	TEXT NOT NULL,
	"Typ"	TEXT NOT NULL,
	"RadNr"	INTEGER NOT NULL,
	"Beskrivning"	TEXT,
	"Andelar"	TEXT,
	"Kronor"	REAL DEFAULT 0.0,
	"BilagaRef"	TEXT,
	"OFnot"	TEXT,
	"pairId"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("HuvudmanPnr") REFERENCES "huvudman"("PERSONNUMMER") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "HuvudmanRedogorelse" (
	"ID"	INTEGER,
	"HuvudmanPnr"	TEXT NOT NULL,
	"ArsrakningAr"	INTEGER NOT NULL,
	"redogKalenderarStart"	TEXT,
	"redogKalenderarSlut"	TEXT,
	"redogSlaktskap"	TEXT,
	"redogSlaktskapTyp"	TEXT,
	"redogBoendeform"	TEXT,
	"redogBoendeAnnatText"	TEXT,
	"redogOmfBevakaRatt"	INTEGER,
	"redogOmfForvaltaEgendom"	INTEGER,
	"redogOmfSorjaForPerson"	INTEGER,
	"redogBehovFortsatt"	TEXT,
	"redogAnnanOmfattning"	TEXT,
	"redogAnkBostadsbidrag"	TEXT,
	"redogAnkBostadsbidragKommentar"	TEXT,
	"redogAnkForsorjning"	TEXT,
	"redogAnkForsorjningKommentar"	TEXT,
	"redogAnkHandikapp"	TEXT,
	"redogAnkHandikappKommentar"	TEXT,
	"redogAnkHabilitering"	TEXT,
	"redogAnkHabiliteringKommentar"	TEXT,
	"redogAnkHemtjanst"	TEXT,
	"redogAnkHemtjanstKommentar"	TEXT,
	"redogOmfLSS"	TEXT,
	"redogOmfLSSKommentar"	TEXT,
	"redogPersAssistans"	TEXT,
	"redogPersAssistansKommentar"	TEXT,
	"redogKontaktperson"	TEXT,
	"redogKontaktpersonKommentar"	TEXT,
	"redogHemforsakring"	TEXT,
	"redogHemforsakringKommentar"	TEXT,
	"redogAvvecklatBostad"	TEXT,
	"redogAvvecklatBostadKommentar"	TEXT,
	"redogKostnadOmsorg"	TEXT,
	"redogKostnadOmsorgKommentar"	TEXT,
	"redogForbehallBelopp"	TEXT,
	"redogForbehallBeloppKommentar"	TEXT,
	"redogTecknatHyresavtal"	TEXT,
	"redogTecknatHyresavtalKommentar"	TEXT,
	"redogAnsoktNyttBoende"	TEXT,
	"redogAnsoktNyttBoendeKommentar"	TEXT,
	"redogEkonomiOvrigtSoktFondmedel_Text"	TEXT,
	"redogAntalBesokTyp"	TEXT,
	"redogVistelseUtanforHemmet"	TEXT,
	"redogVistelseUtanforHemmetDetaljer"	TEXT,
	"redogAntalTelefonsamtal"	TEXT,
	"redogAntalKontakterAnhoriga"	TEXT,
	"redogOvrigaInsatserText"	TEXT,
	"redogBetalningInternetbank"	INTEGER,
	"redogBetalningAutogiro"	INTEGER,
	"redogKontooverforingHm"	INTEGER,
	"redogKontanterHmKvitto"	INTEGER,
	"redogKontooverforingBoende"	INTEGER,
	"redogKontanterBoendeKvitto"	INTEGER,
	"redogForvaltningSaltKoptFastighet"	TEXT,
	"redogForvaltningSaltKoptFastighetKommentar"	TEXT,
	"redogForvaltningHyrtUtFastighet"	TEXT,
	"redogForvaltningHyrtUtFastighetKommentar"	TEXT,
	"redogForvaltningSaltKoptAktier"	TEXT,
	"redogForvaltningSaltKoptAktierKommentar"	TEXT,
	"redogForvaltningAnnanVardepapper"	TEXT,
	"redogForvaltningAnnanVardepapperKommentar"	TEXT,
	"redogForvaltningSoktSkuldsanering"	TEXT,
	"redogForvaltningSoktSkuldsaneringKommentar"	TEXT,
	"redogForvaltningOvrigt1"	TEXT,
	"redogForvaltningOvrigt2"	TEXT,
	"redogArvodeBevakaRatt"	INTEGER,
	"redogArvodeForvaltaEgendom"	INTEGER,
	"redogArvodeSorjaForPerson"	INTEGER,
	"redogArbetsinsats"	TEXT,
	"redogOnskarKostnadsersattning"	TEXT,
	"redogReseersattningKm"	TEXT,
	"redogKorjournalBifogas"	TEXT,
	"redogArvodeOvrigt"	TEXT,
	"redogUnderskriftDatum"	TEXT,
	"redogUnderskriftOrt"	TEXT,
	UNIQUE("HuvudmanPnr","ArsrakningAr"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "HuvudmanSkulder" (
	"ID"	INTEGER,
	"HuvudmanPnr"	TEXT NOT NULL,
	"RadNr"	INTEGER NOT NULL,
	"Langivare"	TEXT,
	"BilagaRef"	TEXT,
	"StartBelopp"	REAL DEFAULT 0.0,
	"SlutBelopp"	REAL DEFAULT 0.0,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("HuvudmanPnr") REFERENCES "huvudman"("PERSONNUMMER") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Kategoriregler" (
	"ID"	INTEGER,
	"MatchningsTyp"	TEXT NOT NULL,
	"MatchningsText"	TEXT NOT NULL,
	"Kategori"	TEXT NOT NULL,
	"Prioritet"	INTEGER DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Overformyndare" (
	"ID"	INTEGER,
	"Namn"	TEXT UNIQUE,
	"Adress"	TEXT,
	"Postnummer"	TEXT,
	"Postort"	TEXT,
	"Telefon"	TEXT,
	"Epost"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PdfFieldMappings" (
	"ID"	INTEGER,
	"TemplateID"	INTEGER NOT NULL,
	"PdfFieldName"	TEXT NOT NULL,
	"DbColumnName"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	UNIQUE("TemplateID","PdfFieldName"),
	FOREIGN KEY("TemplateID") REFERENCES "PdfTemplates"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "PdfTemplates" (
	"ID"	INTEGER,
	"TemplateName"	TEXT NOT NULL UNIQUE,
	"OriginalFilename"	TEXT NOT NULL,
	"StoredFilename"	TEXT NOT NULL,
	"CreatedAt"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "huvudman" (
	"PERSONNUMMER"	TEXT NOT NULL,
	"FORNAMN"	TEXT,
	"EFTERNAMN"	TEXT,
	"HELT_NAMN"	TEXT,
	"ADRESS"	TEXT,
	"POSTNUMMER"	TEXT,
	"ORT"	TEXT,
	"VISTELSEADRESS"	TEXT,
	"VISTELSEPOSTNR"	TEXT,
	"VISTELSEORT"	TEXT,
	"TELEFON"	TEXT,
	"MOBIL"	TEXT,
	"EPOST"	TEXT,
	"MEDBORGARSKAP"	TEXT,
	"CIVILSTAND"	TEXT,
	"SAMMANBOENDE"	INTEGER,
	"MEDSOKANDE_FORNAMN"	TEXT,
	"MEDSOKANDE_EFTERNAMN"	TEXT,
	"MEDSOKANDE_PERSONNUMMER"	TEXT,
	"MEDSOKANDE_MEDBORGARSKAP"	TEXT,
	"MEDSOKANDE_CIVILSTAND"	TEXT,
	"MEDSOKANDE_SYSSELSATTNING"	TEXT,
	"CLEARINGNUMMER"	TEXT,
	"KONTONUMMER"	TEXT,
	"BANKNAMN"	TEXT,
	"OVERFORMYNDARE_ID"	INTEGER,
	"BOENDE_NAMN"	TEXT,
	"BOSTAD_TYP"	TEXT,
	"BOSTAD_ANTAL_RUM"	INTEGER,
	"BOSTAD_ANTAL_BOENDE"	INTEGER,
	"BOSTAD_KONTRAKTSTID"	TEXT,
	"SYSSELSATTNING"	TEXT,
	"INKOMSTTYP"	TEXT,
	"DEKLARERAT_STATUS"	TEXT,
	"ARVODE_UTBETALT_STATUS"	INTEGER,
	"MERKOSTNADSERSTATTNING_STATUS"	INTEGER,
	"ARSR_OVRIGA_UPPLYSNINGAR"	TEXT,
	"ERSATTNING_ANNAN_MYNDIGHET_STATUS"	INTEGER,
	"ERSATTNING_ANNAN_MYNDIGHET_FRAN"	TEXT,
	"HYRA"	REAL,
	"EL_KOSTNAD"	REAL,
	"FACK_AVGIFT_AKASSA"	REAL,
	"RESKOSTNADER"	REAL,
	"HEMFORSAKRING"	REAL,
	"MEDICIN_KOSTNAD"	REAL,
	"LAKARVARDSKOSTNAD"	REAL,
	"BARNOMSORG_AVGIFT"	REAL,
	"FARDTJANST_AVGIFT"	REAL,
	"AKUT_TANDVARDSKOSTNAD"	REAL,
	"BREDBAND"	REAL,
	"OVRIG_KOSTNAD_BESKRIVNING"	TEXT,
	"OVRIG_KOSTNAD_BELOPP"	REAL,
	"ARBETSLOSHETSERSTATTNING"	REAL,
	"AVTALSFOrSAKRING_AFA"	REAL,
	"BARNBIDRAG_STUDIEBIDRAG"	REAL,
	"BOSTADSBIDRAG"	REAL,
	"ETABLERINGSERSATTNING"	REAL,
	"BARNS_INKOMST"	REAL,
	"HYRESINTAKT_INNEBOENDE"	REAL,
	"LON"	REAL,
	"PENSION_LIVRANTA_SJUK_AKTIVITET"	REAL,
	"SJUKPENNING_FORALDRAPENNING"	REAL,
	"SKATTEATERBARING"	REAL,
	"STUDIEMEDEL"	REAL,
	"UNDERHALLSSTOD_EFTERLEVANDEPENSION"	REAL,
	"VANTAD_INKOMST_BESKRIVNING"	TEXT,
	"VANTAD_INKOMST_BELOPP"	REAL,
	"OVRIG_INKOMST_BESKRIVNING"	TEXT,
	"OVRIG_INKOMST_BELOPP"	REAL,
	"TILLGANG_BANKMEDEL_VARDE"	REAL,
	"TILLGANG_BOSTADSRATT_FASTIGHET_VARDE"	REAL,
	"TILLGANG_FORDON_MM_VARDE"	REAL,
	"SKULD_KFM_VARDE"	REAL,
	"FORORDNANDE_DATUM"	TEXT,
	"SALDO_RAKNINGSKONTO_FORORDNANDE"	REAL,
	"HANDLAGGARE"	TEXT,
	PRIMARY KEY("PERSONNUMMER")
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER,
	"username"	TEXT NOT NULL UNIQUE,
	"password_hash"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
