// "C:\Users\lars-\gman-web\js\modules\constants.js";
export const PDF_FIELD_MAP = {
  Personnummer: "personnummer",
  Fornamn: "fornamn",
  Efternamn: "efternamn",
  HeltNamn: "heltNamn",
  MedsokandePersonnummer: "medsokandePersonnummer",
  MedsokandeFornamn: "medsokandeFornamn",
  MedsokandeEfternamn: "medsokandeEfternamn",
  Adress: "adress",
  Postnummer: "postnummer",
  Ort: "ort",
  BoendeNamn: "boendeNamn",
  BostadAntalRum: "bostadAntalrum",
  BostadAntalBoende: "bostadAntalBoende",
  Sysselsattning: "sysselsattning",
  ArsrOvrigaUpplysningar: "ovrigaUpplysningar",
  Hyra: "hyra",
  Bredband: "bredband",
  FackAvgiftAkassa: "fackAvgiftAkassa",
  Hemforsakring: "hemforsakring",
  Reskostnader: "reskostnader",
  ElKostnad: "elKostnad",
  MedicinKostnad: "medicinkostnad",
  Lakarvardskostnad: "lakarvardkostnad",
  BarnomsorgAvgift: "barnomsorgAvgift",
  FardtjanstAvgift: "fardtjanstAvgift",
  OvrigKostnadBeskrivning: "ovrigKostnadBeskrivning",
  OvrigKostnadBelopp: "ovrigKostnadBelopp",
};

export const ALL_KATEGORIER = {
  LönerPensioner: {
    namn: "Brutto inkomst som löner, pensioner m.m.",
    typ: "inkomst",
    postKod: "LONERPENSIONER",
    justerbar: true,
  },
  BostadstilläggBidrag: {
    namn: "Bostadstillägg/Bostadsbidrag",
    typ: "inkomst",
    postKod: "BOSTADSTILLAGG",
  },
  HABErsättning: { namn: "HAB ersättning", typ: "inkomst", postKod: "HAB" },
  RäntaBankkonto: { namn: "Ränta bankkonto", typ: "inkomst", postKod: "RANTA" },
  Utdelning: { namn: "Utdelning", typ: "inkomst", postKod: "UTDELNING" },
  UttagFonderFörsäljAktier: {
    namn: "Uttag fonder Försäljning aktier",
    typ: "inkomst",
    postKod: "UTTAGFONDER",
  },
  ÅterbetalningarInkomst: {
    namn: "Återbetalningar",
    typ: "inkomst",
    postKod: "ATERBETALNING",
  },
  ArvInkomst: { namn: "Arv", typ: "inkomst", postKod: "ARV" },
  InsättningAnhörig: {
    namn: "Insättning anhörig",
    typ: "inkomst",
    postKod: "INSATTANHORIG",
  },
  Hyresinkomst: { namn: "Hyres inkomst", typ: "inkomst", postKod: "HYRES" },
  Skatteåterbäring: {
    namn: "Skatteåterbäring",
    typ: "inkomst",
    postKod: "SKATTATER",
  },
  ÖverföringEgetKontoIn: {
    namn: "Överföring Till Räkningskontot(inkomst)",
    typ: "inkomst",
    postKod: "OVERFORINGEGET_IN",
  },
  ÖvrigInkomst: {
    namn: "Övrig inkomst",
    typ: "inkomst",
    postKod: "OVRIG_INKOMST",
  },
  PreliminärSkattInk: {
    namn: "Preliminär skatt beskattningsbar ink. m.m.",
    typ: "utgift",
    postKod: "PRELSKATTINK",
  },
  PreliminärSkattRänta: {
    namn: "Preliminär skatt ränta utdelning",
    typ: "utgift",
    postKod: "PRELSKATTRANTA",
  },
  HyraBoendeMat: {
    namn: "Hyra/boende/mat",
    typ: "utgift",
    postKod: "HYRABOENDEMAT",
  },
  Försäkringar: { namn: "Försäkringar", typ: "utgift", postKod: "FORSAKRING" },
  TVTeleEl: { namn: "TV/Tele/El", typ: "utgift", postKod: "TVTELEEL" },
  SjukvårdLäkarbesökApotek: {
    namn: "Sjukhusvård, läkarbesök, apotek",
    typ: "utgift",
    postKod: "SJUKVARD",
  },
  KöpAktierFonder: {
    namn: "Köp av aktier, fonder",
    typ: "utgift",
    postKod: "KOPAKTIER",
  },
  AmorteringSkuldAvgift: {
    namn: "Amortering skuld, skuldräntor & avgifter, KFM",
    typ: "utgift",
    postKod: "AMORTERING",
  },
  MedelEgetBrukUttag: {
    namn: "Medel för eget bruk/Eget uttag",
    typ: "utgift",
    postKod: "EGETBRUK",
  },
  ArvodeStällföreträdare: {
    namn: "Arvode ställföreträdare inkl. soc. avg. och utlägg",
    typ: "utgift",
    postKod: "ARVODE",
  },
  Färdtjänst: { namn: "Färdtjänst", typ: "utgift", postKod: "FARDTJANST" },
  FackAvgAKassa: {
    namn: "Fack avg/A-kassan",
    typ: "utgift",
    postKod: "FACKAKASSA",
  },
  Föreningsavgifter: {
    namn: "Föreningsavgifter",
    typ: "utgift",
    postKod: "FORENING",
  },
  CSNUtgift: { namn: "CSN", typ: "utgift", postKod: "CSN_UTGIFT" },
  Tidningar: { namn: "Tidningar", typ: "utgift", postKod: "TIDNING" },
  Bankavgifter: { namn: "Bankavgifter", typ: "utgift", postKod: "BANKAVGIFT" },
  Kvarskatt: { namn: "Kvarskatt", typ: "utgift", postKod: "KVARSKATT" },
  ÖverföringEgetKontoUt: {
    namn: "Överföring Från Räkningskontot(utgift)",
    typ: "utgift",
    postKod: "OVERFORINGEGET_UT",
  },
  ÖvrigUtgift: {
    namn: "Övriga utgifter",
    typ: "utgift",
    postKod: "OVRIG_UTGIFT",
  },
  Okategoriserat: { namn: "Okategoriserat", typ: "okänd" },
};

export const KATEGORI_POSTKOD_MAP = {
  LONERPENSIONER: {
    namn: "Brutto inkomst som löner, pensioner m.m.",
    pdfBase: "Inkomst_LonerPensioner",
  },
  BOSTADSTILLAGG: {
    namn: "Bostadstillägg/Bostadsbidrag",
    pdfBase: "Inkomst_Bostadsbidrag",
  },
  HAB: { namn: "HAB ersättning", pdfBase: "Inkomst_HAB" },
  RANTA: { namn: "Ränta bankkonto", pdfBase: "Inkomst_Ranta" },
  UTDELNING: { namn: "Utdelning", pdfBase: "Inkomst_Utdelning" },
  UTTAGFONDER: {
    namn: "Uttag fonder Försäljning aktier",
    pdfBase: "Inkomst_UttagFonder",
  },
  ATERBETALNING: { namn: "Återbetalningar", pdfBase: "Inkomst_Aterbetalning" },
  ARV: { namn: "Arv", pdfBase: "Inkomst_Arv" },
  INSATTANHORIG: { namn: "Insättning anhörig", pdfBase: "Inkomst_Anhorig" },
  HYRES: { namn: "Hyres inkomst", pdfBase: "Inkomst_Hyres" },
  SKATTATER: { namn: "Skatteåterbäring", pdfBase: "Inkomst_Skatt" },
  OVERFORINGEGET_IN: {
    namn: "Överföringar eget konto",
    pdfBase: "Inkomst_Overforing",
  },
  OVRIG_INKOMST: { namn: "Övrig inkomst", pdfBase: "Inkomst_Ovrig" },
  PRELSKATTINK: {
    namn: "Preliminär skatt beskattningsbar ink. m.m.",
    pdfBase: "Utgift_PrelSkattInk",
  },
  PRELSKATTRANTA: {
    namn: "Preliminär skatt ränta utdelning",
    pdfBase: "Utgift_PrelSkattRanta",
  },
  HYRABOENDEMAT: { namn: "Hyra/boende/mat", pdfBase: "Utgift_HyraBoendeMat" },
  FORSAKRING: { namn: "Försäkringar", pdfBase: "Utgift_Forsakring" },
  TVTELEEL: { namn: "TV/Tele/El", pdfBase: "Utgift_TVTeleEl" },
  SJUKVARD: {
    namn: "Sjukhusvård, läkarbesök, apotek",
    pdfBase: "Utgift_Sjukvard",
  },
  KOPAKTIER: { namn: "Köp av aktier, fonder", pdfBase: "Utgift_KopAktier" },
  AMORTERING: {
    namn: "Amortering skuld, skuldräntor & avgifter, KFM",
    pdfBase: "Utgift_Amortering",
  },
  EGETBRUK: {
    namn: "Medel för eget bruk/Eget uttag",
    pdfBase: "Utgift_EgetBruk",
  },
  ARVODE: {
    namn: "Arvode ställföreträdare inkl. soc. avg. och utlägg",
    pdfBase: "Utgift_Arvode",
  },
  FARDTJANST: { namn: "Färdtjänst", pdfBase: "Utgift_Fardtjanst" },
  FACKAKASSA: { namn: "Fack avg/A-kassan", pdfBase: "Utgift_FackAvgKassa" },
  FORENING: { namn: "Föreningsavgifter", pdfBase: "Utgift_Foreningsavgifter" },
  CSN_UTGIFT: { namn: "CSN", pdfBase: "Utgift_CSN" },
  TIDNING: { namn: "Tidningar", pdfBase: "Utgift_Tidning" },
  BANKAVGIFT: { namn: "Bankavgifter", pdfBase: "Utgift_Bankavgift" },
  KVARSKATT: { namn: "Kvarskatt", pdfBase: "Utgift_Kvarskatt" },
  OVERFORINGEGET_UT: {
    namn: "Överföringar eget konto",
    pdfBase: "Utgift_Overforing",
  },
  OVRIG_UTGIFT: { namn: "Övriga utgifter", pdfBase: "Utgift_Ovrig" },
};

export const API = {
  OF_LIST: "api/get_overformyndare.php",
  HM_LIST: "api/get_all_huvudman.php",
  HM_STATS: "api/get_dashboard_stats.php",
  PROFILES: "api/get_godman_profiles.php",
  HM_DASH: "api/get_huvudman_dashboard.php",
  HM_DETAILS: "api/get_huvudman_details.php",
};
